name       : python3-gobject
version    : 3.26.1
release    : 13
source     :
    - https://download.gnome.org/sources/pygobject/3.26/pygobject-3.26.1.tar.xz : f5577b9b9c70cabb9a60d81b855d488b767c66f867432e7fb64aa7269b04d1a9
license    : GPL-2.0
component  : programming.python
summary    : Python API to GObject Introspection
description: |
    Provides access to GObject Introspection libraries within Python3 applications
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(py3cairo)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
