name        : python3-gobject
version     : 3.16.1
release     : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/pygobject/3.16/pygobject-3.16.1.tar.xz : 7d96dad050f15ec1688617b749bb485811842de46a22d31f9396023e8eaa1ec3
license     : GPL-2.0+
summary     : Python API to GObject Introspection
builddeps   :
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
description : |
    Provides access to GObject Introspection libraries within Python3 applications
setup      : |
    %configure --disable-static --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
