name       : python3-gobject
version    : 3.32.2
release    : 16
source     :
    - https://download.gnome.org/sources/pygobject/3.32/pygobject-3.32.2.tar.xz : c39ca2a28364b57fa00549c6e836346031e6b886c3ceabfd8ab4b4fed0a83611
license    : GPL-2.0-only
component  : programming.python
summary    : Python API to GObject Introspection
description: |
    Provides access to GObject Introspection libraries within Python3 applications
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(py3cairo)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
