name       : python3-gobject
version    : 3.24.1
release    : 9
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/pygobject/3.24/pygobject-3.24.1.tar.xz : a628a95aa0909e13fb08230b1b98fc48adef10b220932f76d62f6821b3fdbffd
license    : GPL-2.0
component  : programming.python
summary    : Python API to GObject Introspection
description: |
    Provides access to GObject Introspection libraries within Python3 applications
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(py3cairo)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
