name       : python3-gobject
version    : 3.34.0
release    : 17
source     :
    - https://download.gnome.org/sources/pygobject/3.34/pygobject-3.34.0.tar.xz : 87e2c9aa785f352ef111dcc5f63df9b85cf6e05e52ff04f803ffbebdacf5271a
license    : GPL-2.0-only
component  : programming.python
summary    : Python API to GObject Introspection
description: |
    Provides access to GObject Introspection libraries within Python3 applications
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(py3cairo)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
