name       : python3-gobject
version    : 3.26.0
release    : 10
source     :
    - https://download.gnome.org/sources/pygobject/3.26/pygobject-3.26.0.tar.xz : 7411acd600c8cb6f00d2125afa23303f2104e59b83e0a4963288dbecc3b029fa
license    : GPL-2.0
component  : programming.python
summary    : Python API to GObject Introspection
description: |
    Provides access to GObject Introspection libraries within Python3 applications
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(py3cairo)
setup      : |
    %configure --disable-static --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
