name        : python3-gobject
version     : 3.18.2
release     : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/pygobject/3.18/pygobject-3.18.2.tar.xz : 2a3cad1517916b74e131e6002c3824361aee0671ffb0d55ded119477fc1c2c5f
license     : GPL-2.0+
summary     : Python API to GObject Introspection
builddeps   :
    - pkgconfig(python-3.4)
    - pkgconfig(py3cairo)
description : |
    Provides access to GObject Introspection libraries within Python3 applications
setup      : |
    %configure --disable-static --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
