name       : python3-gobject
version    : 3.22.0
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/pygobject/3.22/pygobject-3.22.0.tar.xz : 08b29cfb08efc80f7a8630a2734dec65a99c1b59f1e5771c671d2e4ed8a5cbe7
license    : GPL-2.0+
summary    : Python API to GObject Introspection
builddeps  :
    - pkgconfig(python-3.5)
    - pkgconfig(py3cairo)
component  : programming.python
description: |
    Provides access to GObject Introspection libraries within Python3 applications
setup      : |
    %configure --disable-static --with-python=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
